USE InsuranceDB;
GO

EXEC sp_MSforeachtable "ALTER TABLE ? NOCHECK CONSTRAINT ALL";
GO

DROP TABLE IF EXISTS CLAIM;
DROP TABLE IF EXISTS POLICY;
DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS EVALUATOR;
GO

EXEC sp_MSforeachtable "ALTER TABLE ? CHECK CONSTRAINT ALL";
GO