USE InsuranceDB
GO
DELETE FROM CLAIM;
DELETE FROM EVALUATOR;
DELETE FROM CUSTOMER;
DELETE FROM POLICY;

USE insurance
DELETE FROM CLAIM;
DELETE FROM CLAIM_NO;
DELETE FROM CATEGORY;
DELETE FROM DEPARTMENT;
DELETE FROM CATEGORY;
DELETE FROM DEPARTMENT;
DELETE FROM EVALUATOR;
DELETE FROM SENIORITY;