CREATE DATABASE insurance;

use  insurance
GO

CREATE TABLE CATEGORY (
    CategoryID INTEGER IDENTITY(1,1) PRIMARY KEY,
    CategoryName VARCHAR(255) NOT NULL
);

CREATE TABLE SENIORITY (
    SeniorityCategoryID INTEGER IDENTITY(1,1) PRIMARY KEY,
    SeniorityCategoryName VARCHAR(255) NOT NULL
);

CREATE TABLE DEPARTMENT (
    DepartmentID INTEGER IDENTITY(1,1) PRIMARY KEY,
    DepartmentName VARCHAR(255) NOT NULL
);

CREATE TABLE EVALUATOR (
    EvaluatorID INTEGER IDENTITY(1,1) PRIMARY KEY,
    PESEL CHAR(11) NOT NULL,
    FirstName VARCHAR(255) NOT NULL,
    LastName VARCHAR(255) NOT NULL,
    DepartmentID INTEGER NOT NULL FOREIGN KEY REFERENCES DEPARTMENT(DepartmentID),
    Position VARCHAR(255) NOT NULL,
    SeniorityCategoryID INTEGER NOT NULL FOREIGN KEY REFERENCES SENIORITY(SeniorityCategoryID),
    IsCurrent BIT NOT NULL
);

CREATE TABLE JUNK (
    JunkID INTEGER IDENTITY(1,1) PRIMARY KEY,
    IsAccepted VARCHAR(255) NOT NULL
);

CREATE TABLE CLAIM_NO (
	ClaimNoID INTEGER IDENTITY(1,1) PRIMARY KEY,
	ClaimNo  VARCHAR(255)
);

CREATE TABLE DATE (
    ID INTEGER IDENTITY(1,1) PRIMARY KEY,
    Day SMALLINT CHECK (Day BETWEEN 1 AND 31),
    MonthNumber SMALLINT CHECK (MonthNumber BETWEEN 1 AND 12),
    MonthName VARCHAR(255) NOT NULL,
    Quarter SMALLINT CHECK (Quarter BETWEEN 1 AND 4),
    Year INT CHECK (Year > 0),
    Date DATE NOT NULL
);

CREATE TABLE CLAIM (
    ResultDateID INTEGER NOT NULL FOREIGN KEY REFERENCES DATE(ID),
    EvaluatorID INTEGER NOT NULL FOREIGN KEY  REFERENCES EVALUATOR(EvaluatorID),
    CategoryID INTEGER NOT NULL FOREIGN KEY  REFERENCES CATEGORY(CategoryID),
	ClaimNoID INTEGER NOT NULL FOREIGN KEY  REFERENCES CLAIM_NO(ClaimNoID),
    ProcessingTime NUMERIC,
    ClaimAmount NUMERIC,
    SettlementAmount NUMERIC,
    JunkID INTEGER NOT NULL FOREIGN KEY REFERENCES JUNK(JunkID),
    CONSTRAINT composite_pk PRIMARY KEY (ResultDateID, EvaluatorID, CategoryID, JunkID)
);